# Generated by Django 5.0.2 on 2024-02-27 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'admin_detail',
            },
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'brand_table',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category_table',
            },
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
            ],
            options={
                'db_table': 'event_table',
            },
        ),
        migrations.CreateModel(
            name='ProductConditionModel',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'condition_table',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=35)),
                ('model_number', models.CharField(max_length=35)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brandmodel')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.categorymodel')),
                ('condition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.productconditionmodel')),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.categorymodel')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.productmodel')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_to', models.CharField(max_length=20)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.eventmodel')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.productmodel')),
            ],
            options={
                'db_table': 'discount_table',
            },
        ),
        migrations.CreateModel(
            name='SpecificationModel',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('ram', models.CharField(max_length=20)),
                ('rom', models.CharField(max_length=20)),
                ('camera', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('colour', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.productmodel')),
            ],
            options={
                'db_table': 'specification_table',
            },
        ),
    ]
