# Generated by Django 5.0.2 on 2024-02-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='categor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.categorymodel'),
        ),
        migrations.AlterField(
            model_name='specificationmodel',
            name='battery',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
