# Generated by Django 5.0.2 on 2024-03-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_brandmodel_categor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationmodel',
            name='model_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specificationmodel',
            name='operating_system',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specificationmodel',
            name='screen_size',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='specificationmodel',
            name='version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specificationmodel',
            name='camera',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
