# Generated by Django 5.0.2 on 2024-03-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_specificationmodel_model_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.imagemodel'),
        ),
    ]
