# Generated by Django 5.0.2 on 2024-03-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_imagemodel_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
