# Generated by Django 5.0.2 on 2024-03-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_imagemodel_img1_imagemodel_img2_imagemodel_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='event_img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
