# Generated by Django 5.0.2 on 2024-03-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_alter_ordermodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
