# Generated by Django 5.0.2 on 2024-03-15 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_ordermodel_address_alter_ordermodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel'),
        ),
    ]
