# Generated by Django 5.0.2 on 2024-03-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_ordermodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
