# Generated by Django 5.0.2 on 2024-03-20 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_remove_ordermodel_address_ordermodel_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel'),
        ),
    ]
