# Generated by Django 5.0.2 on 2024-03-22 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_imagemodel_img1_imagemodel_img2_imagemodel_img3'),
        ('UserApp', '0010_feedbackmodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='oder_id',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='spec_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.specificationmodel'),
        ),
    ]
