# Generated by Django 5.0.2 on 2024-04-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_remove_feedbackmodel_oder_id_feedbackmodel_spec_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
