# Generated by Django 5.0.2 on 2024-04-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_alter_usermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
